// <auto-generated />
using System;
using Deployment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deployment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DeploymentDbContext))]
    partial class DeploymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Deployment.Domain.Configuration.ConfigurationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeployableUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeployableUnitId", "EnvironmentId", "Key")
                        .IsUnique()
                        .HasFilter("[EnvironmentId] IS NOT NULL");

                    b.ToTable("ConfigurationSetting", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConfigurationSetting_SecretShape", "([IsSecret] = 1 AND [Value] IS NULL AND [SecretReference] IS NOT NULL) OR ([IsSecret] = 0 AND [SecretReference] IS NULL AND [Value] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.ApplicationService", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeploymentOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApplicationId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ApplicationService", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.DeployableUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UnitType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeployableUnit", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApproverPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.ToTable("Approval", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OverrideFreezeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ParentDeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RolledBackByDeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkipPromotionPathReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Strategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredByPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentDeploymentId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("EnvironmentId", "Status", "CompletedAtUtc");

                    b.HasIndex("TargetId", "Status", "CompletedAtUtc");

                    b.ToTable("Deployment", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.DeploymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId", "Timestamp");

                    b.ToTable("DeploymentEvent", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.DeploymentSecretBinding", b =>
                {
                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfigurationSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolvedSecretUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DeploymentId", "ConfigurationSettingId");

                    b.HasIndex("ConfigurationSettingId");

                    b.ToTable("DeploymentSecretBinding", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Environments.DeploymentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TargetKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Region");

                    b.ToTable("DeploymentTarget", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Environments.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PromotionRank")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PromotionRank");

                    b.ToTable("Environment", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Environments.EnvironmentFreezeWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "StartUtc", "EndUtc");

                    b.ToTable("EnvironmentFreezeWindow", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Releases.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("int");

                    b.Property<string>("ArtifactUri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeployableUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeployableUnitId", "SemanticVersion")
                        .IsUnique();

                    b.HasIndex("DeployableUnitId", "Status");

                    b.ToTable("Release", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.Releases.ReleaseComposition", b =>
                {
                    b.Property<Guid>("ApplicationReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PinMode")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServiceReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationReleaseId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceReleaseId");

                    b.ToTable("ReleaseComposition", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReleaseComposition_PinMode", "([PinMode] = 0 AND [ServiceReleaseId] IS NOT NULL) OR ([PinMode] IN (1,2) AND [ServiceReleaseId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Deployment.Infrastructure.Persistence.Projections.ConfigurationSettingHistoryRow", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedByPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ConfigurationSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("NewIsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("NewSecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("NewValueType")
                        .HasColumnType("int");

                    b.Property<bool?>("OldIsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("OldSecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("OldValueType")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("ConfigurationSettingId", "ChangedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ConfigurationSettingHistory", (string)null);
                });

            modelBuilder.Entity("Deployment.Infrastructure.Persistence.Projections.ReleaseStatusChangeRow", b =>
                {
                    b.Property<Guid>("ChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedByPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("ChangeId");

                    b.HasIndex("ReleaseId", "ChangedAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ReleaseStatusChange", (string)null);
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.Application", b =>
                {
                    b.HasOne("Deployment.Domain.DeployableUnits.DeployableUnit", "Unit")
                        .WithOne()
                        .HasForeignKey("Deployment.Domain.DeployableUnits.Application", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.ApplicationService", b =>
                {
                    b.HasOne("Deployment.Domain.DeployableUnits.Application", null)
                        .WithMany("Services")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.Service", b =>
                {
                    b.HasOne("Deployment.Domain.DeployableUnits.DeployableUnit", "Unit")
                        .WithOne()
                        .HasForeignKey("Deployment.Domain.DeployableUnits.Service", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.Approval", b =>
                {
                    b.HasOne("Deployment.Domain.Deployments.Deployment", null)
                        .WithMany("Approvals")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.Deployment", b =>
                {
                    b.HasOne("Deployment.Domain.Deployments.Deployment", null)
                        .WithMany()
                        .HasForeignKey("ParentDeploymentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.DeploymentEvent", b =>
                {
                    b.HasOne("Deployment.Domain.Deployments.Deployment", null)
                        .WithMany("Events")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.DeploymentSecretBinding", b =>
                {
                    b.HasOne("Deployment.Domain.Deployments.Deployment", null)
                        .WithMany("SecretBindings")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.Environments.DeploymentTarget", b =>
                {
                    b.HasOne("Deployment.Domain.Environments.Environment", null)
                        .WithMany("Targets")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.Environments.EnvironmentFreezeWindow", b =>
                {
                    b.HasOne("Deployment.Domain.Environments.Environment", null)
                        .WithMany("FreezeWindows")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.Releases.Release", b =>
                {
                    b.OwnsOne("Deployment.Domain.Releases.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("ReleaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ArtifactSha256")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnName("ArtifactSha256");

                            b1.Property<string>("CiRunId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CiRunId");

                            b1.Property<string>("CiRunUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("CiRunUrl");

                            b1.Property<string>("PublishedByPrincipal")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PublishedByPrincipal");

                            b1.Property<string>("SbomUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SbomUri");

                            b1.Property<string>("VulnerabilityReportUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("VulnerabilityReportUri");

                            b1.HasKey("ReleaseId");

                            b1.ToTable("Release");

                            b1.WithOwner()
                                .HasForeignKey("ReleaseId");
                        });

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("Deployment.Domain.Releases.ReleaseComposition", b =>
                {
                    b.HasOne("Deployment.Domain.Releases.Release", null)
                        .WithMany("Compositions")
                        .HasForeignKey("ApplicationReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Deployment.Domain.DeployableUnits.Application", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Deployment.Domain.Deployments.Deployment", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Events");

                    b.Navigation("SecretBindings");
                });

            modelBuilder.Entity("Deployment.Domain.Environments.Environment", b =>
                {
                    b.Navigation("FreezeWindows");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Deployment.Domain.Releases.Release", b =>
                {
                    b.Navigation("Compositions");
                });
#pragma warning restore 612, 618
        }
    }
}
