// <auto-generated />
using System;
using Jenkins.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jenkins.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JenkinsCiDbContext))]
    partial class JenkinsCiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Jenkins.Domain.Builds.ArtifactPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Registry")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("BuildArtifactId");

                    b.ToTable("ArtifactPublication", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CiBuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CiJobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CiRunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CiRunUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CiJobName", "CiBuildNumber")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "StartedAtUtc");

                    b.ToTable("Build", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProducedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("BuildArtifact", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.DeployableComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeployableUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeployableUnitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ContainerName")
                        .IsUnique();

                    b.ToTable("DeployableComponent", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.SourceRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CiJobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceRepository", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.ArtifactPublication", b =>
                {
                    b.HasOne("Jenkins.Domain.Builds.BuildArtifact", null)
                        .WithMany("Publications")
                        .HasForeignKey("BuildArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.OwnsOne("Jenkins.Domain.Builds.BuildQuality", "Quality", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SbomUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("SbomUri");

                            b1.Property<string>("VulnerabilityReportUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("VulnerabilityReportUri");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.OwnsOne("Jenkins.Domain.Builds.BuildVersions", "Versions", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AssemblyVersion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AssemblyVersion");

                            b1.Property<string>("BaseVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("BaseVersion");

                            b1.Property<string>("FileVersion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("FileVersion");

                            b1.Property<string>("InformationalVersion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("InformationalVersion");

                            b1.Property<string>("PackageVersion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("PackageVersion");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.OwnsOne("Jenkins.Domain.Builds.SourceRevision", "SourceRevision", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Author")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("CommitAuthor");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Branch");

                            b1.Property<string>("CommitSha")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("CommitSha");

                            b1.Property<string>("CommitShort")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("CommitShort");

                            b1.Property<DateTimeOffset?>("CommittedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("CommittedAtUtc");

                            b1.Property<string>("Message")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("CommitMessage");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.Navigation("Quality");

                    b.Navigation("SourceRevision")
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.HasOne("Jenkins.Domain.Builds.Build", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.DeployableComponent", b =>
                {
                    b.HasOne("Jenkins.Domain.SourceRepositories.SourceRepository", null)
                        .WithMany("Components")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.SourceRepository", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
